sudo: required
services: -docker

before_install:
  - docker build -t menelik7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true menelik7/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-237483526022"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: "$AWS_SECRET_KEY"
